// Import your components and styles
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from './components/Navbar';
import { Footer } from './components/Footer';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={inter.className}>
        <head>
            {/* Meta tags and other head elements can be placed here */}
        </head>
        <body>
        <Navbar />
        {/* Adjust mt- value according to your navbar's actual height */}
        <main className="">{children}</main>
        <Footer />
        </body>
        </html>
    );
}
